artifacts_root: artifacts

#for data ingestion config 
data_ingestion:
  root_dir: artifacts/data_ingestion    # create a directory name data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip  # define the source url
  local_data_file: artifacts/data_ingestion/data.zip   # store the data as a zip formal 
  unzip_dir: artifacts/data_ingestion   # store the data in uzip format in that directory



data_validation:
  root_dir: artifacts/data_validation  # create a directory name data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv   # retrive the data from the unzip data 
  STATUS_FILE: artifacts/data_validation/status.txt   # then check the status of the data from the schemafile and store the output to the status file 


data_transformation:
  root_dir: artifacts/data_transformation   #create a directory name data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv # it is the path of the data 


model_trainer:
  root_dir: artifacts/model_trainer   #create a directory name odel_trainer
  train_data_path: artifacts/data_transformation/train.csv  # it is the path of the training_data 
  test_data_path: artifacts/data_transformation/test.csv    # it is the path of the test_data
  model_name: model.joblib    # model save file



model_evaluation:
  root_dir: artifacts/model_evaluation        #create a directory name odel_trainer
  test_data_path: artifacts/data_transformation/test.csv        # it is the path of the test_data
  model_path: artifacts/model_trainer/model.joblib             # it is the path of the model
  metric_file_name: artifacts/model_evaluation/metrics.json      # here i store the evaluation metrics
